import { useEffect, useState } from "react";
import AdProductForm from "./add-product-form";
// as you can see, we are using the methods and types generated by hey-api
import { getProducts, type Product } from "./client";

const ProductsListViaClient = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Please use tanstack/query instead of useEffect for any async operations to avoid a lot of bugs
  useEffect(() => {
    const fetchProducts = async () => {
      try {
        setIsLoading(true);
        // getProduct is the same as the Operation Id
        const response = await getProducts();
        setProducts(response.data || []);
      } catch (err) {
        setError("Failed to fetch products");
        console.error("Error fetching products:", err);
      } finally {
        setIsLoading(false);
      }
    };

    fetchProducts();
  }, []);

  if (isLoading) {
    return (
      <div className='flex items-center justify-center mt-10'>
        <div className='animate-spin h-10 w-10 border-b-4 border-blue-500 rounded-full'></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className='flex items-center justify-center mt-10'>
        <div className='text-red-500 text-lg'>{error}</div>
      </div>
    );
  }

  return (
    <div className='bg-linear-to-br from-slate-50 to-blue-50 py-8 px-4'>
      <div className='max-w-7xl mx-auto'>
        <div className='text-center mb-12'>
          <h1 className='text-5xl font-bold bg-linear-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent mb-4'>
            Our Products
          </h1>
        </div>

        <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6'>
          <AdProductForm />
          {products.map((product) => (
            <ProductItem key={product.id} product={product} />
          ))}
        </div>
      </div>
    </div>
  );
};

type ProductItemProps = {
  product: Product;
};

function ProductItem({ product }: ProductItemProps) {
  return (
    <div className='group bg-white rounded-2xl shadow-lg hover:shadow-2xl transition-all duration-300 hover:-translate-y-2 overflow-hidden border border-gray-100'>
      <div className='h-48 bg-linear-to-br from-blue-100 to-purple-100 flex items-center justify-center'>
        <div className='text-4xl text-blue-500 opacity-20 group-hover:scale-110 transition-transform duration-300'>
          🛍️
        </div>
      </div>

      <div className='p-6'>
        <h2 className='text-xl font-bold text-gray-800 mb-3 line-clamp-2 group-hover:text-blue-600 transition-colors'>
          {product.title}
        </h2>

        <p className='text-gray-600 text-sm mb-4 line-clamp-3 leading-relaxed'>
          {product.description}
        </p>

        <div className='flex items-center justify-between mt-auto'>
          <span className='text-2xl font-bold bg-linear-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent'>
            {(product.price / 100).toFixed(2)} LE
          </span>
        </div>
      </div>
    </div>
  );
}

export default ProductsListViaClient;
